/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ILArt } from "./ILArt";
export * as factories from "./factories";
export { ILArt__factory } from "./factories/ILArt__factory";
